yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Страницы сообществ(group)
    path('group/<slug:slug>/', views.group_posts, name='group_list')
]

yatube/yatube/urls.py
from django.contrib import admin
# импорт include позволит использовать адреса, включенные в приложения
from django.urls import include, path

urlpatterns = [
    # Сначала проверяем все пути, которые есть в приложении posts
    path('', include('posts.urls', namespace='posts')),
    # Дорогой Джанго, если на сервер пришёл запрос ('group/'),
    # перейди в файл urls приложения posts
    # и проверь там все path() на совпадение с запрошенным URL
    path('group/', include('posts.urls')),
    path('admin/', admin.site.urls)
    ]

yatube/posts/models.py
from django.db import models
# Из модуля auth импортируем функцию get_user_model
from django.contrib.auth import get_user_model

'''
В этом фаиле описываются предметы(модели) того, 
что будет размещаться в админке и наделяются свойствами.
'''
User = get_user_model()


class Group(models.Model):
    # при печати объекта модели Group выводилось поле title
    def __str__(self):
        return self.title
    # Название группы
    title = models.CharField(max_length=200)
    # Отображение ссылки по slug
    slug = models.SlugField()
    # Описание сообщества
    description = models.TextField()


# Здесь мы задаем поля и параметры вывода полей для БД
class Post(models.Model):
    # Поле для хранения пользовательских данных
    text = models.TextField()
    # Поле для хранения даты и времени
    pub_date = models.DateTimeField(auto_now_add=True)
    # ссылка на другую таблицу, на её primary key (pk).
    # это свойство обеспечивает связь (relation) между таблицами баз данных.
    author = models.ForeignKey(
        User,
        # обеспечивает связность данных: если из таблицы User
        # будет удалён пользователь и будут удалены все связанные с ним посты.
        on_delete=models.CASCADE,
        related_name='posts'
    )
    # свойство group, чтобы при добавлении новой записи,
    # можно было сослаться на сообщество (на модель Group)
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        # обеспечивает связность данных: если из таблицы Group
        # будет удалён пользователь и будут удалены все связанные с ним посты.
        on_delete=models.SET_NULL,
        related_name='groups'
    )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404

# Импортируем модель, чтобы обратиться к ней
from .models import Post, Group
'''
В этом фаиле обрабатываются запросы к страницам
'''

def index(request):
    title = 'Последние обновления на сайте'
    # Одна строка вместо тысячи слов на SQL:
    # в переменную posts будет сохранена выборка из 10 объектов модели Post,
    # отсортированных по полю pub_date по убыванию
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        # В словарь можно передать переменную
        'title': title,
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    title = 'Записи сообщества Лев Толстой – зеркало русской революции'
    # Функция ищет в базе объект модели, а если не находит,
    # прерывает работу view-функции и возвращает страницу с ошибкой 404.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе
    group = get_object_or_404(Group, slug=slug)
    # Метод .filter позволяет ограничить поиск по критериям.
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'title': title,
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>{{ title }}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
<footer class="page-footer font-small blue border-top">
    <div class="footer-copyright text-center py-3">© 2020 Copyright 
      <p><span style="color:red">Ya</span>tube</p> 
    </div>    

yatube/templates/includes/header.html
{% load static %}
  <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
  <!-- В дальнейшем тут будет создано полноценное меню -->    
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index'%}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:red">Ya</span>tube
        </a>
      </div>
    </nav>      

yatube/templates/posts/group_list.html
<!-- Это мы говорим брять всю инфу с главного шаблона -->
{% extends 'base.html' %} 

<!-- Это тег шаблонизатора include, сюда будет включён код
из файла includes/header.html -->
{% include 'includes/header.html' %}

<!-- Это то, что описано на главной странице в блоке main -->
{% block content %}
<div class="container py-5">
  {% for post in posts %}
  <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>      
      <p>
        {{ post.text }}
      </p>
      {% if not forloop.last %} <hr> {% endif %}
  {% endfor %}
  </article>
</div>  
{% endblock %}

<!-- Это то, что описано в includes/footer.html -->
{% include 'includes/footer.html' %} 

yatube/templates/posts/index.html
<!-- Это мы говорим брять всю инфу с главного шаблона -->
{% extends 'base.html' %} 

<!-- Это тег шаблонизатора include, сюда будет включён код
из файла includes/header.html -->
{% include 'includes/header.html' %}

<!-- Это то, что описано на главной странице в блоке main -->
{% block content %}
<div class="container py-5">
  {% for post in posts %}
  <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>      
      <p>
        {{ post.text }}
      </p>
      {% if post.group %} 
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %} <hr> {% endif %}
  {% endfor %}
  </article>      
</div> 
{% endblock %}

<!-- Это то, что описано в includes/footer.html -->
{% include 'includes/footer.html' %} 